stages:
    - linting

flake8:
    stage: linting
    image: python:3.12-slim-bullseye
    script:
        - pip install flake8
        - pip install flake8-quotes
        - pip install pep8-naming
        - pip install flake8-import-order
        - flake8 --verbose .

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check --diff --skip-string-normalization .
