stages:
    - linting
    - test

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - pip install -r requirements/test.txt
        - flake8 --verbose .

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check --diff .

http_response:
    stage: test
    image: registry.gitlab.com/python-devs/ci-images:active
    cache:
        paths:
            - .cache/pip
    before_script:
        - python -m venv venv
        - source venv/bin/activate
        - pip install -r requirements/prod.txt
    script:
        - cd lyceum
        - python manage.py test
