# Generated by Django 4.2.16 on 2024-11-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='имя',
                    ),
                ),
                (
                    'mail',
                    models.EmailField(max_length=100, verbose_name='почта'),
                ),
                ('text', models.TextField(verbose_name='текст')),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name='время создания',
                    ),
                ),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
