# Generated by Django 4.2.16 on 2024-11-13 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'Новый'),
                    ('wip', 'В процессе'),
                    ('ans', 'Отвечен'),
                ],
                default='new',
                max_length=3,
                verbose_name='статус',
            ),
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='время'
                    ),
                ),
                (
                    'from_status',
                    models.CharField(
                        db_column='from',
                        max_length=3,
                        verbose_name='из статуса',
                    ),
                ),
                (
                    'to',
                    models.CharField(
                        db_column='to', max_length=3, verbose_name='в статус'
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='status_logs',
                        to='feedback.feedback',
                        verbose_name='отзыв',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'лог статуса',
                'verbose_name_plural': 'логи статусов',
            },
        ),
    ]
