# Generated by Django 4.2.16 on 2024-11-13 11:22

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_status_statuslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        upload_to=feedback.models.feedback_directory_path,
                        verbose_name='файл',
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='feedback.feedback',
                    ),
                ),
            ],
            options={
                'verbose_name': 'прикрепленный файл',
                'verbose_name_plural': 'прикрепленные файлы',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAuthor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='имя',
                    ),
                ),
                (
                    'mail',
                    models.EmailField(max_length=100, verbose_name='почта'),
                ),
                (
                    'feedback',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='author',
                        to='feedback.feedback',
                    ),
                ),
            ],
            options={
                'verbose_name': 'автор отзыва',
                'verbose_name_plural': 'авторы отзывов',
            },
        ),
    ]
