# Generated by Django 4.2.16 on 2024-10-17 08:38

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='опубликовано'
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                'invalid',
                            )
                        ],
                        verbose_name='слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='опубликовано'
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса',
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile('^[-a-zA-Z0-9_]+\\Z'),
                                'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                                'invalid',
                            )
                        ],
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Максимум 150 символов',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='опубликовано'
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='В описании обязательно должно быть слово "превосходно" или "роскошно"',
                        validators=[
                            catalog.models.ValidateContainsWords(
                                'превосходно', 'роскошно'
                            )
                        ],
                        verbose_name='текст',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.category',
                        verbose_name='категория',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        to='catalog.tag', verbose_name='теги'
                    ),
                ),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
