# Generated by Django 4.2.16 on 2024-10-17 07:55

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(
                help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса',
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^[-a-zA-Z0-9_]+\\Z'),
                        'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                        'invalid',
                    )
                ],
                verbose_name='слаг',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='вес',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                to='catalog.tag', verbose_name='теги'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='В описании обязательно должно быть слово "превосходно" или "роскошно"',
                validators=[
                    catalog.models.ValidateContainsWords(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='текст',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='опубликовано'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Максимум 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(
                help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса',
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^[-a-zA-Z0-9_]+\\Z'),
                        'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                        'invalid',
                    )
                ],
                verbose_name='слаг',
            ),
        ),
    ]
