# Generated by Django 4.2.16 on 2024-10-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categories',
            new_name='category',
        ),
    ]
