# Generated by Django 4.2.16 on 2024-10-29 05:23

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_normalized_name_tag_normalized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
        migrations.CreateModel(
            name='ItemMainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        upload_to=core.models.image_directory_path,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'item',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='main_image',
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'главное изображение',
                'verbose_name_plural': 'главные изображения',
            },
        ),
        migrations.CreateModel(
            name='ItemImageGallery',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        upload_to=core.models.image_directory_path,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
