# Generated by Django 4.2.16 on 2024-10-25 08:08

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    replaces = [
        ('catalog', '0003_item_main_image_itemimage_item_images'),
        ('catalog', '0004_remove_item_images'),
    ]

    dependencies = [
        ('catalog', '0002_category_normalized_name_tag_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to='items/main_images/',
                verbose_name='главное изображение',
            ),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    sorl.thumbnail.fields.ImageField(
                        upload_to='items/images/', verbose_name='изображение'
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
