# Generated by Django 4.2.16 on 2024-10-29 06:58

import catalog.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0003_alter_category_id_alter_category_slug_alter_item_id_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text='В описании обязательно должно быть слово "превосходно" или "роскошно"',
                validators=[
                    catalog.validators.ValidateContainsWords(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='текст',
            ),
        ),
    ]
