# Generated by Django 4.2.16 on 2024-11-04 10:23

import catalog.validators
import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0005_item_is_on_main_alter_itemimagegallery_item_squashed_0006_alter_item_category_alter_itemimagegallery_item',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='itemimagegallery',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='itemmainimage',
            options={
                'verbose_name': 'main image',
                'verbose_name_plural': 'main images',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Max 150 symbols',
                max_length=150,
                unique=True,
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                editable=False, max_length=150, verbose_name='normalized name'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Only latin letters, numbers, underscores or hyphens',
                max_length=200,
                unique=True,
                verbose_name='slug',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='weight',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name='items',
                to='catalog.category',
                verbose_name='category',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='on main'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Max 150 symbols',
                max_length=150,
                unique=True,
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                to='catalog.tag', verbose_name='tags'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(
                help_text='The description should contain "превосходно" or "роскошно"',
                validators=[
                    catalog.validators.ValidateContainsWords(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='text',
            ),
        ),
        migrations.AlterField(
            model_name='itemimagegallery',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to=core.models.image_directory_path,
                verbose_name='image',
            ),
        ),
        migrations.AlterField(
            model_name='itemimagegallery',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='catalog.item',
                verbose_name='item',
            ),
        ),
        migrations.AlterField(
            model_name='itemmainimage',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to=core.models.image_directory_path,
                verbose_name='image',
            ),
        ),
        migrations.AlterField(
            model_name='itemmainimage',
            name='item',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='main_image',
                to='catalog.item',
                verbose_name='item',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Max 150 symbols',
                max_length=150,
                unique=True,
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                editable=False, max_length=150, verbose_name='normalized name'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='Only latin letters, numbers, underscores or hyphens',
                max_length=200,
                unique=True,
                verbose_name='slug',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(
                help_text="The description should contain 'превосходно' or 'роскошно'",
                validators=[
                    catalog.validators.ValidateContainsWords(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='text',
            ),
        ),
    ]
