# Generated by Django 4.2.16 on 2024-11-04 12:40

import catalog.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0005_item_is_on_main_alter_itemimagegallery_item_squashed_0006_alter_item_category_alter_itemimagegallery_item',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                verbose_name='нормализованное имя',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(
                help_text="В описании обязательно должно быть слово 'превосходно' или 'роскошно'",
                validators=[
                    catalog.validators.ValidateContainsWords(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='текст',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                verbose_name='нормализованное имя',
            ),
        ),
    ]
