# Generated by Django 4.2.16 on 2024-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0007_alter_category_normalized_name_alter_item_text_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='время создания'
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name='время изменения'
            ),
        ),
    ]
