# Generated by Django 4.2.16 on 2024-11-09 07:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_item_created_item_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={
                'default_related_name': 'items',
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса. Максимум 200 символов',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                help_text='Значение от 1 до 32767',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='вес',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='Только латинские буквы, цифры, знаки подчеркивания или дефиса. Максимум 200 символов',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
    ]
