# Generated by Django 4.2.16 on 2024-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_verbose_names_squashed_0008_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Max 150 symbols',
                max_length=150,
                unique=True,
                verbose_name='title',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Max 150 symbols',
                max_length=150,
                unique=True,
                verbose_name='title',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Max 150 symbols',
                max_length=150,
                unique=True,
                verbose_name='title',
            ),
        ),
    ]
