# Generated by Django 4.2.16 on 2024-11-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_item_options_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimagegallery',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                related_query_name='image',
                to='catalog.item',
                verbose_name='товар',
            ),
        ),
    ]
